export const PAGE_EMPTY = 'PAGE_EMPTY';
export const PAGE_LOGIN = 'PAGE_LOGIN';
export const PAGE_CHAT_LIST = 'PAGE_CHAT_LIST';
export const PAGE_CONFIGURATION = 'PAGE_CONFIGURATION';
export const PAGE_MEMBERS = 'PAGE_MEMBERS';
